// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: orPHpegkXfnsyZCa6kLatK
// Component: bjRtBdfnivza

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: orPHpegkXfnsyZCa6kLatK/projectcss
import sty from "./PlasmicPasswordCheck.module.css"; // plasmic-import: bjRtBdfnivza/css

createPlasmicElementProxy;

export type PlasmicPasswordCheck__VariantMembers = {
  _1Check: "unnamedVariant" | "_2Check";
  unnamedVariant: "unnamedVariant";
};
export type PlasmicPasswordCheck__VariantsArgs = {
  _1Check?: SingleChoiceArg<"unnamedVariant" | "_2Check">;
  unnamedVariant?: SingleBooleanChoiceArg<"unnamedVariant">;
};
type VariantPropType = keyof PlasmicPasswordCheck__VariantsArgs;
export const PlasmicPasswordCheck__VariantProps = new Array<VariantPropType>(
  "_1Check",
  "unnamedVariant"
);

export type PlasmicPasswordCheck__ArgsType = {
  numberOfCheck?: number;
};
type ArgPropType = keyof PlasmicPasswordCheck__ArgsType;
export const PlasmicPasswordCheck__ArgProps = new Array<ArgPropType>(
  "numberOfCheck"
);

export type PlasmicPasswordCheck__OverridesType = {
  passwordCheckWrapper?: Flex__<"div">;
};

export interface DefaultPasswordCheckProps {
  numberOfCheck?: number;
  _1Check?: SingleChoiceArg<"unnamedVariant" | "_2Check">;
  unnamedVariant?: SingleBooleanChoiceArg<"unnamedVariant">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPasswordCheck__RenderFunc(props: {
  variants: PlasmicPasswordCheck__VariantsArgs;
  args: PlasmicPasswordCheck__ArgsType;
  overrides: PlasmicPasswordCheck__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          numberOfCheck: 0
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "_1Check",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props._1Check
      },
      {
        path: "unnamedVariant",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.unnamedVariant
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"passwordCheckWrapper"}
      data-plasmic-override={overrides.passwordCheckWrapper}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.passwordCheckWrapper,
        {
          [sty.passwordCheckWrapper_1Check__2Check]: hasVariant(
            $state,
            "_1Check",
            "_2Check"
          ),
          [sty.passwordCheckWrapper_1Check_unnamedVariant]: hasVariant(
            $state,
            "_1Check",
            "unnamedVariant"
          ),
          [sty.passwordCheckWrapperunnamedVariant]: hasVariant(
            $state,
            "unnamedVariant",
            "unnamedVariant"
          )
        }
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox___4Bb8J, {
          [sty.freeBox_1Check_unnamedVariant___4Bb8JxatFh]: hasVariant(
            $state,
            "_1Check",
            "unnamedVariant"
          )
        })}
      />

      <div className={classNames(projectcss.all, sty.freeBox__nrPXk)} />

      <div className={classNames(projectcss.all, sty.freeBox__suaAr)} />

      <div className={classNames(projectcss.all, sty.freeBox__zI2Mn)} />
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  passwordCheckWrapper: ["passwordCheckWrapper"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  passwordCheckWrapper: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPasswordCheck__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPasswordCheck__VariantsArgs;
    args?: PlasmicPasswordCheck__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPasswordCheck__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicPasswordCheck__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPasswordCheck__ArgProps,
          internalVariantPropNames: PlasmicPasswordCheck__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPasswordCheck__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "passwordCheckWrapper") {
    func.displayName = "PlasmicPasswordCheck";
  } else {
    func.displayName = `PlasmicPasswordCheck.${nodeName}`;
  }
  return func;
}

export const PlasmicPasswordCheck = Object.assign(
  // Top-level PlasmicPasswordCheck renders the root element
  makeNodeComponent("passwordCheckWrapper"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPasswordCheck
    internalVariantProps: PlasmicPasswordCheck__VariantProps,
    internalArgProps: PlasmicPasswordCheck__ArgProps
  }
);

export default PlasmicPasswordCheck;
/* prettier-ignore-end */
